enum ActionType {
  AUTHENTICATE_USER_REQUESTED = "AUTHENTICATE_USER_REQUESTED",
  AUTHENTICATE_USER_SUCCEEDED = "AUTHENTICATE_USER_SUCCEEDED",

  INITIALIZE_CONTENT_REQUESTED = "INITIALIZE_CONTENT_REQUESTED",
  INITIALIZE_CONTENT_SUCCEEDED = "INITIALIZE_CONTENT_SUCCEEDED",
  INITIALIZE_CONTENT_FAILED = "INITIALIZE_CONTENT_FAILED",
}

export default ActionType;
