enum ActionType {
  INITIALIZE_CONTENT_STARTED = "INITIALIZE_CONTENT_STARTED",
  INITIALIZE_CONTENT_SUCCEEDED = "INITIALIZE_CONTENT_SUCCEEDED",
  INITIALIZE_CONTENT_FAILED = "INITIALIZE_CONTENT_FAILED",

  APPLY_TRANSACTION_STARTED = "APPLY_TRANSACTION_STARTED",
  APPLY_TRANSACTION_SUCCEEDED = "APPLY_TRANSACTION_SUCCEEDED",
  APPLY_TRANSACTION_FAILED = "APPLY_TRANSACTION_FAILED",

  PAGE_SELECTED = "PAGE_SELECTED",
}

export default ActionType;
