enum ActionType {
  INITIALIZE_CONTENT_REQUESTED = "INITIALIZE_CONTENT_REQUESTED",
  INITIALIZE_CONTENT_SUCCEEDED = "INITIALIZE_CONTENT_SUCCEEDED",
  INITIALIZE_CONTENT_FAILED = "INITIALIZE_CONTENT_FAILED",
}

export default ActionType;
